; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=1024 -sbvec-allow-non-pow2 \
; RUN:    -sbvec-collect-seeds=loads \
; RUN:    -sbvec-passes="seed-collection<tr-save,top-down-vec,tr-accept>" \
; RUN:    %s -S | FileCheck %s

define void @load_fadd_store(ptr %ptr, ptr %ptr2) {
; CHECK-LABEL: define void @load_fadd_store(
; CHECK-SAME: ptr [[PTR:%.*]], ptr [[PTR2:%.*]]) {
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    [[VEC:%.*]] = fadd <2 x float> [[VECL]], [[VECL]], !sandboxvec [[META0]]
; CHECK-NEXT:    [[PTR2_0:%.*]] = getelementptr float, ptr [[PTR2]], i32 0
; CHECK-NEXT:    store <2 x float> [[VEC]], ptr [[PTR2_0]], align 4, !sandboxvec [[META0]]
; CHECK-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1

  %fadd0 = fadd float %ld0, %ld0
  %fadd1 = fadd float %ld1, %ld1

  %ptr2_0 = getelementptr float, ptr %ptr2, i32 0
  %ptr2_1 = getelementptr float, ptr %ptr2, i32 1
  store float %fadd0, ptr %ptr2_0
  store float %fadd1, ptr %ptr2_1
  ret void
}

define void @load_chain_store(ptr %ptr, ptr %ptr2) {
; CHECK-LABEL: define void @load_chain_store(
; CHECK-SAME: ptr [[PTR:%.*]], ptr [[PTR2:%.*]]) {
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4, !sandboxvec [[META1:![0-9]+]]
; CHECK-NEXT:    [[VEC:%.*]] = fmul <2 x float> [[VECL]], splat (float 3.000000e+00), !sandboxvec [[META1]]
; CHECK-NEXT:    [[VEC1:%.*]] = fadd <2 x float> [[VEC]], splat (float 2.000000e+00), !sandboxvec [[META1]]
; CHECK-NEXT:    [[PTR2_0:%.*]] = getelementptr float, ptr [[PTR2]], i32 0
; CHECK-NEXT:    store <2 x float> [[VEC1]], ptr [[PTR2_0]], align 4, !sandboxvec [[META1]]
; CHECK-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1

  %fmul0 = fmul float %ld0, 3.0
  %fmul1 = fmul float %ld1, 3.0

  %fadd0 = fadd float %fmul0, 2.0
  %fadd1 = fadd float %fmul1, 2.0

  %ptr2_0 = getelementptr float, ptr %ptr2, i32 0
  %ptr2_1 = getelementptr float, ptr %ptr2, i32 1
  store float %fadd0, ptr %ptr2_0
  store float %fadd1, ptr %ptr2_1
  ret void
}

define float @load_fadd_external_use(ptr %ptr, ptr %ptr2) {
; CHECK-LABEL: define float @load_fadd_external_use(
; CHECK-SAME: ptr [[PTR:%.*]], ptr [[PTR2:%.*]]) {
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4, !sandboxvec [[META2:![0-9]+]]
; CHECK-NEXT:    [[VEC:%.*]] = fadd <2 x float> [[VECL]], [[VECL]], !sandboxvec [[META2]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x float> [[VEC]], i32 0, !sandboxvec [[META2]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = extractelement <2 x float> [[VEC]], i32 1, !sandboxvec [[META2]]
; CHECK-NEXT:    [[PTR2_0:%.*]] = getelementptr float, ptr [[PTR2]], i32 0
; CHECK-NEXT:    [[PTR2_1:%.*]] = getelementptr float, ptr [[PTR2]], i32 1
; CHECK-NEXT:    store float [[UNPACK]], ptr [[PTR2_0]], align 4
; CHECK-NEXT:    store float [[UNPACK1]], ptr [[PTR2_1]], align 4
; CHECK-NEXT:    ret float [[UNPACK]]
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1

  %fadd0 = fadd float %ld0, %ld0
  %fadd1 = fadd float %ld1, %ld1

  %ptr2_0 = getelementptr float, ptr %ptr2, i32 0
  %ptr2_1 = getelementptr float, ptr %ptr2, i32 1
  store float %fadd0, ptr %ptr2_0
  store float %fadd1, ptr %ptr2_1

  ret float %fadd0
}
;.
; CHECK: [[META0]] = distinct !{!"sandboxregion"}
; CHECK: [[META1]] = distinct !{!"sandboxregion"}
; CHECK: [[META2]] = distinct !{!"sandboxregion"}
;.
