; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel=0 -mattr=+neon < %s | FileCheck %s --check-prefixes=CHECK,LE,NEON
; RUN: llc -mtriple=aarch64_be-unknown-linux-gnu -global-isel=0 -mattr=+neon < %s | FileCheck %s --check-prefixes=CHECK,BE
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel=0 -mattr=+sve < %s | FileCheck %s --check-prefixes=CHECK,LE,SVE
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel=0 -mattr=+sve2 < %s | FileCheck %s --check-prefixes=CHECK,LE,SVE

define <8 x i8> @sqabs_v8i8(<8 x i8> %x) {
; LE-LABEL: sqabs_v8i8:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.8b, v0.8b
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i8:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8b, v0.8b
; BE-NEXT:    sqabs v0.8b, v0.8b
; BE-NEXT:    rev64 v0.8b, v0.8b
; BE-NEXT:    ret
  %a = call <8 x i8> @llvm.abs.v8i8(<8 x i8> %x, i1 false)
  %r = call <8 x i8> @llvm.umin.v8i8(<8 x i8> %a, <8 x i8> splat (i8 127))
  ret <8 x i8> %r
}

define <16 x i8> @sqabs_v16i8(<16 x i8> %x) {
; LE-LABEL: sqabs_v16i8:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.16b, v0.16b
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v16i8:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.16b, v0.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.16b, v0.16b
; BE-NEXT:    rev64 v0.16b, v0.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <16 x i8> @llvm.abs.v16i8(<16 x i8> %x, i1 false)
  %r = call <16 x i8> @llvm.umin.v16i8(<16 x i8> %a, <16 x i8> splat (i8 127))
  ret <16 x i8> %r
}

define <4 x i16> @sqabs_v4i16(<4 x i16> %x) {
; LE-LABEL: sqabs_v4i16:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.4h, v0.4h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v4i16:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.4h, v0.4h
; BE-NEXT:    sqabs v0.4h, v0.4h
; BE-NEXT:    rev64 v0.4h, v0.4h
; BE-NEXT:    ret
  %a = call <4 x i16> @llvm.abs.v4i16(<4 x i16> %x, i1 false)
  %r = call <4 x i16> @llvm.umin.v4i16(<4 x i16> %a, <4 x i16> splat (i16 32767))
  ret <4 x i16> %r
}

define <8 x i16> @sqabs_v8i16(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.8h, v0.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.8h, v0.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> %a, <8 x i16> splat (i16 32767))
  ret <8 x i16> %r
}

define <2 x i32> @sqabs_v2i32(<2 x i32> %x) {
; LE-LABEL: sqabs_v2i32:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.2s, v0.2s
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v2i32:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.2s, v0.2s
; BE-NEXT:    sqabs v0.2s, v0.2s
; BE-NEXT:    rev64 v0.2s, v0.2s
; BE-NEXT:    ret
  %a = call <2 x i32> @llvm.abs.v2i32(<2 x i32> %x, i1 false)
  %r = call <2 x i32> @llvm.umin.v2i32(<2 x i32> %a, <2 x i32> splat (i32 2147483647))
  ret <2 x i32> %r
}

define <4 x i32> @sqabs_v4i32(<4 x i32> %x) {
; LE-LABEL: sqabs_v4i32:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.4s, v0.4s
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v4i32:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.4s, v0.4s
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.4s, v0.4s
; BE-NEXT:    rev64 v0.4s, v0.4s
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %x, i1 false)
  %r = call <4 x i32> @llvm.umin.v4i32(<4 x i32> %a, <4 x i32> splat (i32 2147483647))
  ret <4 x i32> %r
}

define <1 x i64> @sqabs_v1i64(<1 x i64> %x) {
; CHECK-LABEL: sqabs_v1i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqabs d0, d0
; CHECK-NEXT:    ret
  %a = call <1 x i64> @llvm.abs.v1i64(<1 x i64> %x, i1 false)
  %r = call <1 x i64> @llvm.umin.v1i64(<1 x i64> %a, <1 x i64> splat (i64 9223372036854775807))
  ret <1 x i64> %r
}

define <2 x i64> @sqabs_v2i64(<2 x i64> %x) {
; LE-LABEL: sqabs_v2i64:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.2d, v0.2d
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v2i64:
; BE:       // %bb.0:
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.2d, v0.2d
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <2 x i64> @llvm.abs.v2i64(<2 x i64> %x, i1 false)
  %r = call <2 x i64> @llvm.umin.v2i64(<2 x i64> %a, <2 x i64> splat (i64 9223372036854775807))
  ret <2 x i64> %r
}

define <32 x i8> @sqabs_v32i8(<32 x i8> %x) {
; LE-LABEL: sqabs_v32i8:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.16b, v0.16b
; LE-NEXT:    sqabs v1.16b, v1.16b
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v32i8:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.16b, v0.16b
; BE-NEXT:    rev64 v1.16b, v1.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; BE-NEXT:    sqabs v1.16b, v1.16b
; BE-NEXT:    sqabs v0.16b, v0.16b
; BE-NEXT:    rev64 v0.16b, v0.16b
; BE-NEXT:    rev64 v1.16b, v1.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; BE-NEXT:    ret
  %a = call <32 x i8> @llvm.abs.v32i8(<32 x i8> %x, i1 false)
  %r = call <32 x i8> @llvm.umin.v32i8(<32 x i8> %a, <32 x i8> splat (i8 127))
  ret <32 x i8> %r
}

define <4 x i8> @sqabs_v4i8(<4 x i8> %x) {
; NEON-LABEL: sqabs_v4i8:
; NEON:       // %bb.0:
; NEON-NEXT:    shl v0.4h, v0.4h, #8
; NEON-NEXT:    movi v1.4h, #127
; NEON-NEXT:    sshr v0.4h, v0.4h, #8
; NEON-NEXT:    abs v0.4h, v0.4h
; NEON-NEXT:    umin v0.4h, v0.4h, v1.4h
; NEON-NEXT:    ret
;
; BE-LABEL: sqabs_v4i8:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.4h, v0.4h
; BE-NEXT:    movi v1.4h, #127
; BE-NEXT:    shl v0.4h, v0.4h, #8
; BE-NEXT:    sshr v0.4h, v0.4h, #8
; BE-NEXT:    abs v0.4h, v0.4h
; BE-NEXT:    umin v0.4h, v0.4h, v1.4h
; BE-NEXT:    rev64 v0.4h, v0.4h
; BE-NEXT:    ret
;
; SVE-LABEL: sqabs_v4i8:
; SVE:       // %bb.0:
; SVE-NEXT:    shl v0.4h, v0.4h, #8
; SVE-NEXT:    sshr v0.4h, v0.4h, #8
; SVE-NEXT:    abs v0.4h, v0.4h
; SVE-NEXT:    umin z0.h, z0.h, #127
; SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; SVE-NEXT:    ret
  %a = call <4 x i8> @llvm.abs.v4i8(<4 x i8> %x, i1 false)
  %r = call <4 x i8> @llvm.umin.v4i8(<4 x i8> %a, <4 x i8> splat (i8 127))
  ret <4 x i8> %r
}

define <8 x i16> @sqabs_v8i16_commuted(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16_commuted:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.8h, v0.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_commuted:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.8h, v0.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> splat (i16 32767), <8 x i16> %a)
  ret <8 x i16> %r
}

define <8 x i16> @sqabs_v8i16_poison(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16_poison:
; LE:       // %bb.0:
; LE-NEXT:    sqabs v0.8h, v0.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_poison:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v0.8h, v0.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 true)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> %a, <8 x i16> splat (i16 32767))
  ret <8 x i16> %r
}

define <8 x i16> @sqabs_v8i16_multiuse(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16_multiuse:
; LE:       // %bb.0:
; LE-NEXT:    movi v2.2d, #0000000000000000
; LE-NEXT:    sqabs v1.8h, v0.8h
; LE-NEXT:    saba v1.8h, v0.8h, v2.8h
; LE-NEXT:    mov v0.16b, v1.16b
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_multiuse:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    movi v1.2d, #0000000000000000
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sqabs v2.8h, v0.8h
; BE-NEXT:    saba v2.8h, v0.8h, v1.8h
; BE-NEXT:    rev64 v0.8h, v2.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> %a, <8 x i16> splat (i16 32767))
  %sum = add <8 x i16> %a, %r
  ret <8 x i16> %sum
}

; These are not saturating absolute value: the clamp or comparison differs.
define <8 x i16> @sqabs_v8i16_wrong_clamp(<8 x i16> %x) {
; NEON-LABEL: sqabs_v8i16_wrong_clamp:
; NEON:       // %bb.0:
; NEON-NEXT:    mov w8, #32766 // =0x7ffe
; NEON-NEXT:    abs v0.8h, v0.8h
; NEON-NEXT:    dup v1.8h, w8
; NEON-NEXT:    umin v0.8h, v0.8h, v1.8h
; NEON-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_wrong_clamp:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    mov w8, #32766 // =0x7ffe
; BE-NEXT:    dup v1.8h, w8
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    abs v0.8h, v0.8h
; BE-NEXT:    umin v0.8h, v0.8h, v1.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
;
; SVE-LABEL: sqabs_v8i16_wrong_clamp:
; SVE:       // %bb.0:
; SVE-NEXT:    mov z1.h, #32766 // =0x7ffe
; SVE-NEXT:    abs v0.8h, v0.8h
; SVE-NEXT:    umin v0.8h, v0.8h, v1.8h
; SVE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> %a, <8 x i16> splat (i16 32766))
  ret <8 x i16> %r
}

define <8 x i16> @sqabs_v8i16_signed_min(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16_signed_min:
; LE:       // %bb.0:
; LE-NEXT:    abs v0.8h, v0.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_signed_min:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    abs v0.8h, v0.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.smin.v8i16(<8 x i16> %a, <8 x i16> splat (i16 32767))
  ret <8 x i16> %r
}

define <8 x i16> @sqabs_v8i16_nonuniform(<8 x i16> %x) {
; LE-LABEL: sqabs_v8i16_nonuniform:
; LE:       // %bb.0:
; LE-NEXT:    adrp x8, .LCPI15_0
; LE-NEXT:    abs v0.8h, v0.8h
; LE-NEXT:    ldr q1, [x8, :lo12:.LCPI15_0]
; LE-NEXT:    umin v0.8h, v0.8h, v1.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_v8i16_nonuniform:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    adrp x8, .LCPI15_0
; BE-NEXT:    add x8, x8, :lo12:.LCPI15_0
; BE-NEXT:    ld1 { v1.8h }, [x8]
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    abs v0.8h, v0.8h
; BE-NEXT:    umin v0.8h, v0.8h, v1.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %a = call <8 x i16> @llvm.abs.v8i16(<8 x i16> %x, i1 false)
  %r = call <8 x i16> @llvm.umin.v8i16(<8 x i16> %a, <8 x i16> <i16 32766, i16 32767, i16 32767, i16 32767, i16 32767, i16 32767, i16 32767, i16 32767>)
  ret <8 x i16> %r
}

; The front end may compute the magnitude at twice the lane width.
define <8 x i16> @sqabs_widened(<8 x i16> %x) {
; LE-LABEL: sqabs_widened:
; LE:       // %bb.0:
; LE-NEXT:    sshll2 v2.4s, v0.8h, #0
; LE-NEXT:    sshll v0.4s, v0.4h, #0
; LE-NEXT:    movi v1.4s, #127, msl #8
; LE-NEXT:    abs v0.4s, v0.4s
; LE-NEXT:    abs v2.4s, v2.4s
; LE-NEXT:    smin v2.4s, v2.4s, v1.4s
; LE-NEXT:    smin v0.4s, v0.4s, v1.4s
; LE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; LE-NEXT:    ret
;
; BE-LABEL: sqabs_widened:
; BE:       // %bb.0:
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    movi v1.4s, #127, msl #8
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    sshll2 v2.4s, v0.8h, #0
; BE-NEXT:    sshll v0.4s, v0.4h, #0
; BE-NEXT:    abs v0.4s, v0.4s
; BE-NEXT:    abs v2.4s, v2.4s
; BE-NEXT:    smin v2.4s, v2.4s, v1.4s
; BE-NEXT:    smin v0.4s, v0.4s, v1.4s
; BE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; BE-NEXT:    rev64 v0.8h, v0.8h
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
  %wide = sext <8 x i16> %x to <8 x i32>
  %a = call <8 x i32> @llvm.abs.v8i32(<8 x i32> %wide, i1 false)
  %r = call <8 x i32> @llvm.smin.v8i32(<8 x i32> %a, <8 x i32> splat (i32 32767))
  %narrow = trunc <8 x i32> %r to <8 x i16>
  ret <8 x i16> %narrow
}

; Exercise the expanded compare/bitselect with a different clamp and with a
; nonuniform clamp. Neither is a saturating absolute value.
define <1 x i64> @sqabs_v1i64_wrong_clamp(<1 x i64> %x) {
; NEON-LABEL: sqabs_v1i64_wrong_clamp:
; NEON:       // %bb.0:
; NEON-NEXT:    mov x8, #9223372036854775806 // =0x7ffffffffffffffe
; NEON-NEXT:    abs d0, d0
; NEON-NEXT:    fmov d1, x8
; NEON-NEXT:    cmhi d2, d1, d0
; NEON-NEXT:    bif v0.8b, v1.8b, v2.8b
; NEON-NEXT:    ret
;
; BE-LABEL: sqabs_v1i64_wrong_clamp:
; BE:       // %bb.0:
; BE-NEXT:    mov x8, #9223372036854775806 // =0x7ffffffffffffffe
; BE-NEXT:    abs d0, d0
; BE-NEXT:    fmov d1, x8
; BE-NEXT:    cmhi d2, d1, d0
; BE-NEXT:    bif v0.8b, v1.8b, v2.8b
; BE-NEXT:    ret
;
; SVE-LABEL: sqabs_v1i64_wrong_clamp:
; SVE:       // %bb.0:
; SVE-NEXT:    mov z1.d, #0x7ffffffffffffffe
; SVE-NEXT:    abs d0, d0
; SVE-NEXT:    ptrue p0.d, vl1
; SVE-NEXT:    umin z0.d, p0/m, z0.d, z1.d
; SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; SVE-NEXT:    ret
  %a = call <1 x i64> @llvm.abs.v1i64(<1 x i64> %x, i1 false)
  %r = call <1 x i64> @llvm.umin.v1i64(<1 x i64> %a, <1 x i64> splat (i64 9223372036854775806))
  ret <1 x i64> %r
}

define <2 x i64> @sqabs_v2i64_wrong_clamp(<2 x i64> %x) {
; NEON-LABEL: sqabs_v2i64_wrong_clamp:
; NEON:       // %bb.0:
; NEON-NEXT:    mov x8, #9223372036854775806 // =0x7ffffffffffffffe
; NEON-NEXT:    abs v0.2d, v0.2d
; NEON-NEXT:    dup v1.2d, x8
; NEON-NEXT:    cmhi v2.2d, v1.2d, v0.2d
; NEON-NEXT:    bif v0.16b, v1.16b, v2.16b
; NEON-NEXT:    ret
;
; BE-LABEL: sqabs_v2i64_wrong_clamp:
; BE:       // %bb.0:
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    mov x8, #9223372036854775806 // =0x7ffffffffffffffe
; BE-NEXT:    dup v1.2d, x8
; BE-NEXT:    abs v0.2d, v0.2d
; BE-NEXT:    cmhi v2.2d, v1.2d, v0.2d
; BE-NEXT:    bif v0.16b, v1.16b, v2.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
;
; SVE-LABEL: sqabs_v2i64_wrong_clamp:
; SVE:       // %bb.0:
; SVE-NEXT:    mov z1.d, #0x7ffffffffffffffe
; SVE-NEXT:    abs v0.2d, v0.2d
; SVE-NEXT:    ptrue p0.d, vl2
; SVE-NEXT:    umin z0.d, p0/m, z0.d, z1.d
; SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE-NEXT:    ret
  %a = call <2 x i64> @llvm.abs.v2i64(<2 x i64> %x, i1 false)
  %r = call <2 x i64> @llvm.umin.v2i64(<2 x i64> %a, <2 x i64> splat (i64 9223372036854775806))
  ret <2 x i64> %r
}

define <2 x i64> @sqabs_v2i64_nonuniform(<2 x i64> %x) {
; NEON-LABEL: sqabs_v2i64_nonuniform:
; NEON:       // %bb.0:
; NEON-NEXT:    adrp x8, .LCPI19_0
; NEON-NEXT:    abs v0.2d, v0.2d
; NEON-NEXT:    ldr q1, [x8, :lo12:.LCPI19_0]
; NEON-NEXT:    cmhi v2.2d, v1.2d, v0.2d
; NEON-NEXT:    bif v0.16b, v1.16b, v2.16b
; NEON-NEXT:    ret
;
; BE-LABEL: sqabs_v2i64_nonuniform:
; BE:       // %bb.0:
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    adrp x8, .LCPI19_0
; BE-NEXT:    add x8, x8, :lo12:.LCPI19_0
; BE-NEXT:    ld1 { v1.2d }, [x8]
; BE-NEXT:    abs v0.2d, v0.2d
; BE-NEXT:    cmhi v2.2d, v1.2d, v0.2d
; BE-NEXT:    bif v0.16b, v1.16b, v2.16b
; BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; BE-NEXT:    ret
;
; SVE-LABEL: sqabs_v2i64_nonuniform:
; SVE:       // %bb.0:
; SVE-NEXT:    adrp x8, .LCPI19_0
; SVE-NEXT:    abs v0.2d, v0.2d
; SVE-NEXT:    ptrue p0.d, vl2
; SVE-NEXT:    ldr q1, [x8, :lo12:.LCPI19_0]
; SVE-NEXT:    umin z0.d, p0/m, z0.d, z1.d
; SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE-NEXT:    ret
  %a = call <2 x i64> @llvm.abs.v2i64(<2 x i64> %x, i1 false)
  %r = call <2 x i64> @llvm.umin.v2i64(<2 x i64> %a, <2 x i64> <i64 9223372036854775806, i64 9223372036854775807>)
  ret <2 x i64> %r
}
