; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals smart
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

define i32 @test_fold(i1 %c, i32 %fv) {
; CHECK-LABEL: @test_fold(
; CHECK-NEXT:    [[NEWSI:%.*]] = select i1 [[C:%.*]], i32 15, i32 10, !prof [[PROF1:![0-9]+]]
; CHECK-NEXT:    [[OP:%.*]] = add i32 [[NEWSI]], [[FV:%.*]]
; CHECK-NEXT:    ret i32 [[OP]]
;
  %tv = add i32 %fv, 5
  %sel = select i1 %c, i32 %tv, i32 %fv, !prof !0
  %op = add i32 %sel, 10
  ret i32 %op
}

!0 = !{!"branch_weights", i32 10, i32 90}
;.
; CHECK: [[PROF1]] = !{!"branch_weights", i32 10, i32 90}
;.
