; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals --prefix-filecheck-ir-name true
; RUN: opt -mtriple=nvptx-unknown-unknown -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefix=CHECK

; ModuleID = '/app/example.cu'
target datalayout = "e-p6:32:32-i64:64-i128:128-i256:256-v16:16-v32:32-n16:32:64"

@_ZZ27mcasi_digit_counters_kernelE14shared_storage = internal addrspace(3) global [256 x i32] undef, align 4

; Function Attrs: convergent mustprogress noinline norecurse nounwind
;.
; CHECK: @_ZZ27mcasi_digit_counters_kernelE14shared_storage = internal addrspace(3) global [256 x i32] undef, align 4
;.
define dso_local ptx_kernel void @mcasi_digit_counters_kernel(ptr nofree noundef writeonly captures(none) %0, ptr nofree noundef readonly captures(none) %1, i32 noundef %2) local_unnamed_addr #0 {
; CHECK: Function Attrs: convergent mustprogress noinline norecurse nounwind
; CHECK-LABEL: define {{[^@]+}}@mcasi_digit_counters_kernel
; CHECK-SAME: (ptr nofree noundef writeonly captures(none) [[TMP0:%.*]], ptr nofree noundef readonly captures(none) [[TMP1:%.*]], i32 noundef [[TMP2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP4:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #[[ATTR4:[0-9]+]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp samesign ult i32 [[TMP5]], 256
; CHECK-NEXT:    br i1 [[TMP6]], label [[TMP7:%.*]], label [[TMP14:%.*]]
; CHECK:       7:
; CHECK-NEXT:    [[TMP8:%.*]] = zext nneg i32 [[TMP5]] to i64
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[TMP1]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = addrspacecast ptr [[TMP9]] to ptr addrspace(1)
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(1) [[TMP10]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw [4 x i8], ptr addrspacecast (ptr addrspace(3) @_ZZ27mcasi_digit_counters_kernelE14shared_storage to ptr), i64 [[TMP8]]
; CHECK-NEXT:    [[TMP13:%.*]] = addrspacecast ptr [[TMP12]] to ptr addrspace(3)
; CHECK-NEXT:    store i32 [[TMP11]], ptr addrspace(3) [[TMP13]], align 4
; CHECK-NEXT:    br label [[TMP14]]
; CHECK:       14:
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier.cta.sync.aligned.all(i32 noundef 0)
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr noalias nofree noundef nonnull align 8 captures(none) dereferenceable(32) [[TMP4]]) #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    [[TMP15:%.*]] = shl nuw nsw i32 [[TMP5]], 2
; CHECK-NEXT:    [[TMP16:%.*]] = and i32 [[TMP15]], 124
; CHECK-NEXT:    [[TMP17:%.*]] = zext nneg i32 [[TMP16]] to i64
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw [4 x i8], ptr addrspacecast (ptr addrspace(3) @_ZZ27mcasi_digit_counters_kernelE14shared_storage to ptr), i64 [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = addrspacecast ptr [[TMP4]] to ptr addrspace(5)
; CHECK-NEXT:    store ptr [[TMP18]], ptr addrspace(5) [[TMP19]], align 8
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP18]], i64 4
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP4]], i64 8
; CHECK-NEXT:    [[TMP22:%.*]] = addrspacecast ptr [[TMP21]] to ptr addrspace(5)
; CHECK-NEXT:    store ptr [[TMP20]], ptr addrspace(5) [[TMP22]], align 8
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP18]], i64 8
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP4]], i64 16
; CHECK-NEXT:    [[TMP25:%.*]] = addrspacecast ptr [[TMP24]] to ptr addrspace(5)
; CHECK-NEXT:    store ptr [[TMP23]], ptr addrspace(5) [[TMP25]], align 8
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP18]], i64 12
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP4]], i64 24
; CHECK-NEXT:    [[TMP28:%.*]] = addrspacecast ptr [[TMP27]] to ptr addrspace(5)
; CHECK-NEXT:    store ptr [[TMP26]], ptr addrspace(5) [[TMP28]], align 8
; CHECK-NEXT:    [[TMP29:%.*]] = and i32 [[TMP2]], 3
; CHECK-NEXT:    [[TMP30:%.*]] = zext nneg i32 [[TMP29]] to i64
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw [8 x i8], ptr [[TMP4]], i64 [[TMP30]]
; CHECK-NEXT:    [[TMP32:%.*]] = addrspacecast ptr [[TMP31]] to ptr addrspace(5)
; CHECK-NEXT:    [[TMP33:%.*]] = load ptr, ptr addrspace(5) [[TMP32]], align 8
; CHECK-NEXT:    [[TMP34:%.*]] = addrspacecast ptr [[TMP33]] to ptr addrspace(3)
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr addrspace(3) [[TMP34]], align 4, !invariant.load [[META15:![0-9]+]]
; CHECK-NEXT:    [[TMP36:%.*]] = add i32 [[TMP35]], [[TMP29]]
; CHECK-NEXT:    [[TMP37:%.*]] = zext nneg i32 [[TMP5]] to i64
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[TMP0]], i64 [[TMP37]]
; CHECK-NEXT:    [[TMP39:%.*]] = addrspacecast ptr [[TMP38]] to ptr addrspace(1)
; CHECK-NEXT:    store i32 [[TMP36]], ptr addrspace(1) [[TMP39]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr noalias nofree noundef nonnull align 8 captures(none) dereferenceable(32) [[TMP4]]) #[[ATTR5]]
; CHECK-NEXT:    ret void
;
  %4 = alloca [4 x ptr], align 8
  %5 = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  %6 = icmp samesign ult i32 %5, 256
  br i1 %6, label %7, label %12

7:                                                ; preds = %3
  %8 = zext nneg i32 %5 to i64
  %9 = getelementptr inbounds nuw [4 x i8], ptr %1, i64 %8
  %10 = load i32, ptr %9, align 4
  %11 = getelementptr inbounds nuw [4 x i8], ptr addrspacecast (ptr addrspace(3) @_ZZ27mcasi_digit_counters_kernelE14shared_storage to ptr), i64 %8
  store i32 %10, ptr %11, align 4
  br label %12

12:                                               ; preds = %7, %3
  tail call void @llvm.nvvm.barrier.cta.sync.aligned.all(i32 0)
  call void @llvm.lifetime.start.p0(ptr nonnull %4) #4
  %13 = shl nuw nsw i32 %5, 2
  %14 = and i32 %13, 124
  %15 = zext nneg i32 %14 to i64
  %16 = getelementptr inbounds nuw [4 x i8], ptr addrspacecast (ptr addrspace(3) @_ZZ27mcasi_digit_counters_kernelE14shared_storage to ptr), i64 %15
  store ptr %16, ptr %4, align 8
  %17 = getelementptr inbounds nuw i8, ptr %16, i64 4
  %18 = getelementptr inbounds nuw i8, ptr %4, i64 8
  store ptr %17, ptr %18, align 8
  %19 = getelementptr inbounds nuw i8, ptr %16, i64 8
  %20 = getelementptr inbounds nuw i8, ptr %4, i64 16
  store ptr %19, ptr %20, align 8
  %21 = getelementptr inbounds nuw i8, ptr %16, i64 12
  %22 = getelementptr inbounds nuw i8, ptr %4, i64 24
  store ptr %21, ptr %22, align 8
  %23 = and i32 %2, 3
  %24 = zext nneg i32 %23 to i64
  %25 = getelementptr inbounds nuw [8 x i8], ptr %4, i64 %24
  %26 = load ptr, ptr %25, align 8
  %27 = load i32, ptr %26, align 4
  %28 = add i32 %27, %23
  %29 = zext nneg i32 %5 to i64
  %30 = getelementptr inbounds nuw [4 x i8], ptr %0, i64 %29
  store i32 %28, ptr %30, align 4
  call void @llvm.lifetime.end.p0(ptr nonnull %4) #4
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(ptr captures(none)) #1

; Function Attrs: convergent nocallback nounwind
declare void @llvm.nvvm.barrier.cta.sync.aligned.all(i32) #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.nvvm.read.ptx.sreg.tid.x() #3

attributes #0 = { convergent mustprogress noinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_120a" "target-features"="+ptx91,+sm_120a" "uniform-work-group-size" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { convergent nocallback nounwind }
attributes #3 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.dbg.cu = !{!5}
!llvm.ident = !{!7, !8}
!llvm.errno.tbaa = !{!9}
!nvvmir.version = !{!14}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 13, i32 1]}
!1 = !{i32 7, !"Dwarf Version", i32 2}
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !6, producer: "clang version 23.0.0git (https://github.com/llvm/llvm-project.git 774f8a0b868cf526ffbd8af0a7e83c6b70d1b4fb)", isOptimized: true, runtimeVersion: 0, emissionKind: DebugDirectivesOnly, splitDebugInlining: false, nameTableKind: None)
!6 = !DIFile(filename: "/app/example.cu", directory: "/app")
!7 = !{!"clang version 23.0.0git (https://github.com/llvm/llvm-project.git 774f8a0b868cf526ffbd8af0a7e83c6b70d1b4fb)"}
!8 = !{!"clang version 3.8.0 (tags/RELEASE_380/final)"}
!9 = !{!10, !11, i64 0}
!10 = !{!"__libc_errno", !11, i64 0}
!11 = !{!"int", !12, i64 0}
!12 = !{!"omnipotent char", !13, i64 0}
!13 = !{!"Simple C++ TBAA"}
!14 = !{i32 2, i32 0}
;.
; CHECK: attributes #[[ATTR0]] = { convergent mustprogress noinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_120a" "target-features"="+ptx91,+sm_120a" "uniform-work-group-size" }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { convergent nocallback nounwind }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR4]] = { willreturn }
; CHECK: attributes #[[ATTR5]] = { nounwind }
;.
; CHECK: [[META0:![0-9]+]] = !{i32 2, !"SDK Version", [2 x i32] [i32 13, i32 1]}
; CHECK: [[META1:![0-9]+]] = !{i32 7, !"Dwarf Version", i32 2}
; CHECK: [[META2:![0-9]+]] = !{i32 2, !"Debug Info Version", i32 3}
; CHECK: [[META3:![0-9]+]] = !{i32 4, !"nvvm-reflect-ftz", i32 0}
; CHECK: [[META4:![0-9]+]] = !{i32 7, !"frame-pointer", i32 2}
; CHECK: [[META5:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META6:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: true, runtimeVersion: 0, emissionKind: DebugDirectivesOnly, splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META6]] = !DIFile(filename: "{{.*}}example.cu", directory: {{.*}})
; CHECK: [[META7:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
; CHECK: [[META8:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
; CHECK: [[META9:![0-9]+]] = !{[[META10:![0-9]+]], [[META11:![0-9]+]], i64 0}
; CHECK: [[META10]] = !{!"__libc_errno", [[META11]], i64 0}
; CHECK: [[META11]] = !{!"int", [[META12:![0-9]+]], i64 0}
; CHECK: [[META12]] = !{!"omnipotent char", [[META13:![0-9]+]], i64 0}
; CHECK: [[META13]] = !{!"Simple C++ TBAA"}
; CHECK: [[META14:![0-9]+]] = !{i32 2, i32 0}
; CHECK: [[META15]] = !{}
;.
