# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=regbankselect,instruction-select %s -o - | FileCheck %s

---
name: copy_i32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_i32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(i32) = COPY %0(i32)
    RETURN %1(i32), implicit-def $arguments
...

---
name: copy_i64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_i64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(i64) = COPY %0(i64)
    RETURN %1(i64), implicit-def $arguments
...

---
name: copy_f32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_f32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f32_:%[0-9]+]]:f32 = ARGUMENT_f32 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_f32_]], implicit-def $arguments
    %0:f32(f32) = ARGUMENT_f32 0, implicit $arguments
    %1:_(f32) = COPY %0(f32)
    RETURN %1(f32), implicit-def $arguments
...

---
name: copy_f64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_f64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f64_:%[0-9]+]]:f64 = ARGUMENT_f64 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_f64_]], implicit-def $arguments
    %0:f64(f64) = ARGUMENT_f64 0, implicit $arguments
    %1:_(f64) = COPY %0(f64)
    RETURN %1(f64), implicit-def $arguments
...

---
name: copy_to_sp32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_to_sp32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: $sp32 = COPY [[ARGUMENT_i32_]]
    ; CHECK-NEXT: RETURN implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    $sp32 = COPY %0(i32)
    RETURN implicit-def $arguments
...

---
name: copy_to_sp64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_to_sp64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: $sp64 = COPY [[ARGUMENT_i64_]]
    ; CHECK-NEXT: RETURN implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    $sp64 = COPY %0(i64)
    RETURN implicit-def $arguments
...

---
name: copy_from_sp32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_from_sp32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i32 = COPY $sp32
    ; CHECK-NEXT: RETURN [[COPY]], implicit-def $arguments
    %0:_(i32) = COPY $sp32
    RETURN %0(i32), implicit-def $arguments
...

---
name: copy_from_sp64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_from_sp64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i64 = COPY $sp64
    ; CHECK-NEXT: RETURN [[COPY]], implicit-def $arguments
    %0:_(i64) = COPY $sp64
    RETURN %0(i64), implicit-def $arguments
...

---
name: copy_to_fp32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_to_fp32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: $fp32 = COPY [[ARGUMENT_i32_]]
    ; CHECK-NEXT: RETURN implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    $fp32 = COPY %0(i32)
    RETURN implicit-def $arguments
...

---
name: copy_to_fp64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_to_fp64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: $fp64 = COPY [[ARGUMENT_i64_]]
    ; CHECK-NEXT: RETURN implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    $fp64 = COPY %0(i64)
    RETURN implicit-def $arguments
...

---
name: copy_from_fp32
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_from_fp32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i32 = COPY $fp32
    ; CHECK-NEXT: RETURN [[COPY]], implicit-def $arguments
    %0:_(i32) = COPY $fp32
    RETURN %0(i32), implicit-def $arguments
...

---
name: copy_from_fp64
legalized: true
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: copy_from_fp64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i64 = COPY $fp64
    ; CHECK-NEXT: RETURN [[COPY]], implicit-def $arguments
    %0:_(i64) = COPY $fp64
    RETURN %0(i64), implicit-def $arguments
...
