; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i2 @llvm.ucmp.i2.i8(i8, i8)
declare i2 @llvm.ucmp.i2.i16(i16, i16)
declare i2 @llvm.ucmp.i2.i32(i32, i32)
declare i2 @llvm.ucmp.i2.i64(i64, i64)

define i2 @smax_i8(i8 %x, i8 %y) {
; CHECK-LABEL: smax_i8:
; CHECK:         .functype smax_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push11=, 0
; CHECK-NEXT:    i32.const $push8=, 255
; CHECK-NEXT:    i32.and $push5=, $pop11, $pop8
; CHECK-NEXT:    local.get $push12=, 1
; CHECK-NEXT:    i32.const $push7=, 255
; CHECK-NEXT:    i32.and $push6=, $pop12, $pop7
; CHECK-NEXT:    i32.gt_u $push4=, $pop5, $pop6
; CHECK-NEXT:    local.get $push13=, 0
; CHECK-NEXT:    i32.const $push10=, 255
; CHECK-NEXT:    i32.and $push2=, $pop13, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    i32.const $push9=, 255
; CHECK-NEXT:    i32.and $push3=, $pop14, $pop9
; CHECK-NEXT:    i32.lt_u $push1=, $pop2, $pop3
; CHECK-NEXT:    i32.sub $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.ucmp.i2.i8(i8 %x, i8 %y)
  ret i2 %a
}

define i2 @smax_i16(i16 %x, i16 %y) {
; CHECK-LABEL: smax_i16:
; CHECK:         .functype smax_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push11=, 0
; CHECK-NEXT:    i32.const $push8=, 65535
; CHECK-NEXT:    i32.and $push5=, $pop11, $pop8
; CHECK-NEXT:    local.get $push12=, 1
; CHECK-NEXT:    i32.const $push7=, 65535
; CHECK-NEXT:    i32.and $push6=, $pop12, $pop7
; CHECK-NEXT:    i32.gt_u $push4=, $pop5, $pop6
; CHECK-NEXT:    local.get $push13=, 0
; CHECK-NEXT:    i32.const $push10=, 65535
; CHECK-NEXT:    i32.and $push2=, $pop13, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    i32.const $push9=, 65535
; CHECK-NEXT:    i32.and $push3=, $pop14, $pop9
; CHECK-NEXT:    i32.lt_u $push1=, $pop2, $pop3
; CHECK-NEXT:    i32.sub $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.ucmp.i2.i16(i16 %x, i16 %y)
  ret i2 %a
}

define i2 @smax_i32(i32 %x, i32 %y) {
; CHECK-LABEL: smax_i32:
; CHECK:         .functype smax_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.gt_u $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.lt_u $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.ucmp.i2.i32(i32 %x, i32 %y)
  ret i2 %a
}

define i2 @smax_i64(i64 %x, i64 %y) {
; CHECK-LABEL: smax_i64:
; CHECK:         .functype smax_i64 (i64, i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i64.gt_u $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i64.lt_u $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.ucmp.i2.i64(i64 %x, i64 %y)
  ret i2 %a
}
