// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 5
// RUN: llvm-mc -triple=amdgcn -mcpu=gfx1250 -show-encoding %s | FileCheck -check-prefixes=GFX1250 %s
// RUN: llvm-mc -triple=amdgcn -mcpu=gfx1250 -show-encoding %s | %extract-encodings | llvm-mc -triple=amdgcn -mcpu=gfx1250 -disassemble -show-encoding | FileCheck --check-prefixes=GFX1250 %s

s_buffer_load_b64 vcc, s[0:3], s1
// GFX1250: s_buffer_load_b64 vcc, s[0:3], s1 offset:0x0 ; encoding: [0x80,0x3a,0x02,0xf4,0x00,0x00,0x00,0x02]

s_buffer_load_b96 [s104,s105,vcc_lo], s[0:3], s1
// GFX1250: s_buffer_load_b96 [s104,s105,vcc_lo], s[0:3], s1 offset:0x0 ; encoding: [0x00,0xba,0x02,0xf4,0x00,0x00,0x00,0x02]

s_buffer_load_b128 [s104,s105,vcc_lo,vcc_hi], s[0:3], s1
// GFX1250: s_buffer_load_b128 [s104,s105,vcc_lo,vcc_hi], s[0:3], s1 offset:0x0 ; encoding: [0x00,0x5a,0x02,0xf4,0x00,0x00,0x00,0x02]

s_buffer_load_b256 [s100,s101,s102,s103,s104,s105,vcc_lo,vcc_hi], s[0:3], s1
// GFX1250: s_buffer_load_b256 [s100,s101,s102,s103,s104,s105,vcc_lo,vcc_hi], s[0:3], s1 offset:0x0 ; encoding: [0x00,0x79,0x02,0xf4,0x00,0x00,0x00,0x02]

s_buffer_load_b512 [s92,s93,s94,s95,s96,s97,s98,s99,s100,s101,s102,s103,s104,s105,vcc_lo,vcc_hi], s[0:3], s1
// GFX1250: s_buffer_load_b512 [s92,s93,s94,s95,s96,s97,s98,s99,s100,s101,s102,s103,s104,s105,vcc_lo,vcc_hi], s[0:3], s1 offset:0x0 ; encoding: [0x00,0x97,0x02,0xf4,0x00,0x00,0x00,0x02]
